### ISSUE TITLE
TypeScript types support

### ISSUE THREAD

**Issue by LukaszGrela** [hernansartorio/react-nice-dates#10]
> Could not find a declaration file for module 'react-nice-dates'.

Is there a possibility to get the types?

**Comment by hernansartorio** [comment]
How could that be done? I've only used Typescript briefly so I'm not sure what's required for this to work with it.

**Comment by LukaszGrela** [comment]
I think for each file you need to create a `*.d.ts` file that will contain types. Here is a promising answer:
https://stackoverflow.com/questions/12687779/how-do-you-produce-a-d-ts-typings-definition-file-from-an-existing-javascript

**Comment by hernansartorio** [comment]
Thanks, that could work. I have my hands a bit full at the moment, but happy to accept a PR for this.

**Comment by hinsxd** [comment]
I have started rewriting the whole package with some _really minor_ changes to ensure type safety.
I use [tsdx](https://github.com/jaredpalmer/tsdx) to start a new project and basically copy the old code and fix errors.
But I am new to rollup with tsdx and still figure out how to include css files.
AFAIK this package automatically injects the styles when we import any component and this sounds magic to me. Can anyone provide some hints in how to achieve this?

**Comment by hernansartorio** [comment]
@hinsxd CSS is handled separately from Rollup. And the styles are not automatically injected, you have to include the CSS when you use the component (as described in the "Installation" section of the documentation, although I should update the examples to include that too).

**Comment by hinsxd** [comment]
https://github.com/hinsxd/react-nice-dates/tree/typescript
This is my first try in rewriting all components in typescript. There are no breaking changes and it passes all tests. However, there are some major changes in the code including:

1. Replaced constants with typescript enums for better code auto-completion and type safety
2. Used a more robust solution of `useControllableState` from [here](https://github.com/alirezamirian/react-use-controllable-state/blob/master/src/useControllableState.ts)

TODOs:
1. Example website
2. Storybook (This is a really nice tool recommended by the tsdx stack! Perhaps we can replace the whole website with this too. I'm still not too familiar tho :/)
3. Compile css when build. And all publishing stuff.  Maybe we can mess around in a public `alpha` branch published to npm :P 
4. Figure out better way to include styles. (auto include css? break down the css into components? CSS-in-JS? still open-ended...)

Feel free to have a look and help is always wanted!

**Comment by marBerWei** [comment]
Added [this](https://github.com/hernansartorio/react-nice-dates/pull/26) PR - let me know your thoughts!

**Comment by hernansartorio** [comment]
Thank you @marBerWei! Merged #26 and published a new release.
