### ISSUE TITLE
DatePickerCalendar should render preselected date on render

### ISSUE THREAD

**Issue by LukaszGrela** [hernansartorio/react-nice-dates#11]
```
  const [date, setDate] = useState(new Date(2000,0,1));

      // should render 1 jan 2000, but it displays current date
      <DatePickerCalendar date={date} onDateChange={setDate} locale={enGB} />
```

I'm setting up a `DatePickerCalendar` with initial date but caledar is not rendering the preselected date but current date. Is it a bug or I have to "turn some switches" to make it work?

**Comment by hernansartorio** [comment]
Sorry for the delay. Good point, I'll make that the default. For now, with `DatePickerCalendar` you could pass a `month` prop to turn the current month into a controlled prop:

```
const [date, setDate] = useState(new Date(2000,0,1))
const [month, setMonth] = useState(date)

<DatePickerCalendar date={date} month={month} onDateChange={setDate} onMonthChange={setMonth} locale={enGB} />
```

**Comment by maksze** [comment]
@hernansartorio great work! But i have same bug in a DateRangePicker

**Comment by hernansartorio** [comment]
@maksze thanks! Try upgrading to the latest version.
