### ISSUE TITLE
grid not properly calculated on first render (resize triggers proper calculation)

### ISSUE THREAD

**Issue by mkol5222** [hernansartorio/react-nice-dates#14]
Thanks for very nice library.

ISSUE
Using DatePockerCalendar in Ionic React project comes with miscalculated height of day cells and whole grid as shown in attached pictures.

PARTIAL "FIX"
I am unable to find how to wrap or style your component to get proper result.
Resizing window recalculates grid and it starts working as expected with all days visible.

WHAT NEEDS TO BE FIXED - GRID CALCULATION ON FIRST RENDER
Would you please review how to get grid correct on first render?

My wrapper/placement of component in Ionic React app (https://ionicframework.com/docs/react/quickstart).

`<IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Ionic Blank</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <div>
          <DatePickerCalendar locale={cs} date={date} />
        </div>
 </IonContent>
</IonPage >`

Unexpected broken days layout on first render before I try to resize window to force grid recalculation:
![image](https://user-images.githubusercontent.com/229723/73554880-d336ab00-444c-11ea-933e-d13f5d55ab7c.png)

Thanks
Martin

**Comment by hernansartorio** [comment]
Thanks! 

Sorry for the delay.

Huh, is the parent component hidden on mount maybe? The calendar [calculates its height from its width, at mount and when resized](https://github.com/hernansartorio/react-nice-dates/blob/master/src/useGrid.js#L210-L235).

Do you have a live example?
