### ISSUE TITLE
'Customizing days' example showing wrong disabled date

### ISSUE THREAD

**Issue by dheeraj-murali** [hernansartorio/react-nice-dates#19]
**Customizing days** example showing wrong disabled date.
Disabled dates as per example should be Sundays, but in the example they are shown as Saturdays.

need to change the modifiers to fix the issue.

```javascript
// ModifiersExample.js

const modifiers = {
  disabled: date => getDay(date) === 0, // change from 6 to disable Sunday 
  highlight: date => getDay(date) === 2
}
```

Thought this fixes the issue in example, Ideally I feel like the change should be made in how the `CalanderGrid` is laid out.

**Comment by hernansartorio** [comment]
Thanks, I just got confused when writing that comment.

> Ideally I feel like the change should be made in how the CalanderGrid is laid out.
You mean the start of the week day? That depends on the locale you pass, the example uses `enGB`.
