### ISSUE TITLE
Time picker

### ISSUE THREAD

**Issue by startupgurukul** [hernansartorio/react-nice-dates#2]
Thank you for the minimal date picker. 

Coming to the issue, creating a placeholder for time picker (As also requested in HN comments)

Thanks in advance.

**Comment by crobinson42** [comment]
I'm 100% in favor of this also.

**Comment by hernansartorio** [comment]
Added basic support for this in #28, which makes it possible to select the time on the inputs, and makes it easy to integrate with a custom time picking UI (which is out of the scope of this library).

**Comment by deadcoder0904** [comment]
Would love a default Time Picker like Material UI's https://material-ui.com/components/pickers/

I think this is the only thing missing :)
