### ISSUE TITLE
will adding passive flag to touch event listener help?

### ISSUE THREAD

**Issue by kush-agra** [hernansartorio/react-nice-dates#21]
as per https://web.dev/uses-passive-event-listeners/

**Comment by hernansartorio** [comment]
Sorry for the delay. Help with what specifically?

Closing until more clarification is given as this is not describing any issue.

**Comment by kush-agra** [comment]
oops I should have added more context and apologies I don't remember what exactly I meant anymore, but basically lighthouse throws and error and I was probably asking if adding that flag can suppress that without causing any issues

also p.s. love the calendar
