### ISSUE TITLE
make weekday format an optional prop?

### ISSUE THREAD

**Issue by marBerWei** [hernansartorio/react-nice-dates#23]
I noticed that the format of the week day is hard-coded to be "eee". Any chance this could be dynamic and exposed in the API? 

Thanks for this library! It's awesome :)

**Comment by marBerWei** [comment]
Happy to make a PR for this! Let me know if I can get permission to do that :)

**Comment by hernansartorio** [comment]
Oh yes that would be awesome, thank you!

Just push the branch to your own fork and then make a PR from it, let me know if you have any questions!

**Comment by marBerWei** [comment]
Any chance you can help me out with this @hernansartorio ?

`remote: Permission to hernansartorio/react-nice-dates.git denied to marBerWei.`

**Comment by hernansartorio** [comment]
I'm guessing that you're trying to push directly to this repo.

Instead, first you should create a fork of the repo on your account, push your commits there, and then create a PR here against your branch on your repo. Here's [a more detailed guide](https://jarv.is/notes/how-to-pull-request-fork-github/) I found about that. 

Let me know if that helps!

**Comment by marBerWei** [comment]
thanks! should be up now :) let me know what you think!
