### ISSUE TITLE
how to resize nice-dates-popover

### ISSUE THREAD

**Issue by vrambo8** [hernansartorio/react-nice-dates#25]
I can't figure out how to use css to resize the total div popover. I would like to have it half the size, is it possible?

**Comment by SmartAppsX** [comment]
Same problem? Any idea how to resize both width and height? Because only the max-width is not enough for me, and if i use max-height will broke the popover. Thanks

**Comment by hernansartorio** [comment]
Sorry for the delay. You can by overwriting the default CSS in your project, like so:

```CSS
.nice-dates-popover {
  max-width: 480px;
}
```
