### ISSUE TITLE
Remove calendar swipe up/down navigation for mobile devices

### ISSUE THREAD

**Issue by SoulDever** [hernansartorio/react-nice-dates#34]
Hi, it's possibile to disable by prop the up/down swipe on calendar for mobile navigation? 

It creates a problem with scroll on mobile devices. Sometimes when a scroll down (on tap) the calendar goes to next month and select a different date. So I need to change months only by arrows (next/prev). Thanks

**Comment by vonZ** [comment]
Agree on this one, experienced the same behaviour. It would be great to have the possibility to controll this
