### ISSUE TITLE
Consider cross date-libraries compatibility 

### ISSUE THREAD

**Issue by dmtrKovalenko** [hernansartorio/react-nice-dates#4]
Hey, really nice work! 
I am working on [date-io](https://github.com/dmtrKovalenko/date-io) - adapter between different date-management libraries, which can be useful to not require date-fns for all the users, who for example needs time-zone management out of the box, like in [luxon](https://github.com/moment/luxon) or already using [moment](https://github.com/moment/moment), or for example using different from gregorian calendar system.
![image](https://user-images.githubusercontent.com/16926049/72878037-d9b57c00-3d02-11ea-8f0d-aa7392ee45a6.png)

If you find this usefull I can help you integrate date-io :0

**Comment by weyert** [comment]
Wow, this looks like a super useful library! If I understand it correctly this will avoids the need to include multiple date library; because the picker likes moment while you use like luxon or date-fns :D

**Comment by dmtrKovalenko** [comment]
@weyert exactly

**Comment by hernansartorio** [comment]
Thank you!

That looks very useful! However this library depends on date-fns for a lot of things and I'm not sure if it would be worth the effort to adapt it just to save a few Kb.

**Comment by dmtrKovalenko** [comment]
https://bundlephobia.com/result?p=react-nice-dates@1.0.2
Just FUI: you are requiring more date-fns bundlesize than your whole components library.

**Comment by hernansartorio** [comment]
Hm, can you share those numbers?

**Comment by dmtrKovalenko** [comment]
Here you go 
![image](https://user-images.githubusercontent.com/16926049/72931151-077fdc80-3d66-11ea-9ff6-3dff2b033108.png)

react-nice-dates: 16.4kb
bundled date-fns from the first example: 44.23 

Date-fns with one locale require 3 times more space than your components (without styles). Imagine that somebody is already using `moment` or `luxon` for localization. 

Example used to reproduce: 
1. `yarn create react-app`
2. `yarn add react-nice-dates date-fns source-map-explorer`
3. Code for App.js
```js
import React from 'react';
import logo from './logo.svg';
import { enGB } from 'date-fns/locale'
import { DatePicker } from 'react-nice-dates'

function DatePickerExample() {
  const [date, setDate] = React.useState()
  return (
    <DatePicker date={date} onDateChange={setDate} locale={enGB}>
      {({ inputProps, focused }) => (
        <input
          className={'input' + (focused ? ' -focused' : '')}
          {...inputProps}
        />
      )}
    </DatePicker>
  )
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>

      <DatePickerExample />
    </div>
  );
}

export default App;
```
4. Run `yarn build` `yarn source-map-explorer 'build/static/js/*.js'`

**Comment by hernansartorio** [comment]
Oh thank you, that's really neat.

Still I don't think the savings would be worth the effort, but I'll leave the issue open though in case more people request it.

For now I'll look into optimizing the usage of date-fns.

Thanks again!

**Comment by weyert** [comment]
I think the idea is more to be able to safe adding date-fns in the project which will be leveraging your component than saving or optimising the component itself. For example, I typically using Luxon instead of date-fns :)

**Comment by hernansartorio** [comment]
I see, but what would be unsafe about adding date-fns to a project that uses another library?

**Comment by weyert** [comment]
Mainly my project  currently has `momentjs`, `luxon` and `date-fns` as dependencies while it would be nice if people would use date-io adapters so we can avoid adding unnecessary date utilities dependencies to a web application. Less things to be send over the line
