### ISSUE TITLE
handleOutsideClick is throws caught error

### ISSUE THREAD

**Issue by illusional** [hernansartorio/react-nice-dates#53]
This has been blowing up my sentry, I'm not sure why but all I see is `refA.current.contains` is undefined when evaluating: https://github.com/hernansartorio/react-nice-dates/blob/b61f0c77f36b36cc411a24d175dc92ffc286559c/src/useOutsideClickHandler.js#L11-L13

I don't really understand what's causing it, I'm just using it like this:

```jsx
<DatePicker date={this.state.date?.toJSDate()} onDateChange={(date) => this.updateDate(date)} locale={enGB}>
  {({ inputProps, focused }) => (
    <Input
      {...inputProps}
      type="text"
      className={'input' + (focused ? ' -focused' : '')}
    />
  )}
</DatePicker>
```

Suggested fix:

```diff
diff --git a/index.d.ts b/index.d.ts
index 11d03eb..b9ad938 100644
--- a/src/useOutsideClickHandler.js
+++ b/src/useOutsideClickHandler.js
@@ -8,9 +8,9 @@ export default function useOutsideClickHandler(callback) {
   useEffect(() => {
     const handleOutsideClick = event => {
       if (
-        (!refA.current || !refA.current.contains(event.target)) &&
-        (!refB.current || !refB.current.contains(event.target)) &&
-        (!refC.current || !refC.current.contains(event.target))
+         (!refA.current || (refA.current.contains && !refA.current.contains(event.target))) && 
+         (!refB.current || (refB.current.contains && !refB.current.contains(event.target))) && 
+         (!refC.current || (refC.current.contains && !refC.current.contains(event.target)))
       ) {
         callback()
       }
```

**Comment by hernansartorio** [comment]
Hey, sorry for the delay. What does your `Input` component look like? Does clicking an element outside of the date picker close the popover? It might be that the `ref` prop of `inputProps` isn't being forwarded to the actual `input`.

**Comment by illusional** [comment]
Thanks for the reply @hernansartorio! I’m using the input component like the following (same as in the original description):

```

<Input
      {...inputProps}
      type="text"
      className={'input' + (focused ? ' -focused' : '')}
    />
```

Where Input is from Reactstrap.

Is that what you meant?

**Comment by hernansartorio** [comment]
Ah I see, that might be it then. Just approved and merged your PR so at least you won't get the error anymore!
