### ISSUE TITLE
How to set calendar appear above input

### ISSUE THREAD

**Issue by davistran86** [hernansartorio/react-nice-dates#55]
Hi, is there anyway to make the calendar popover stay above the input instead of below it ?
I'm having a select date at near bottom of the page so it would be great to set it above the input

![image](https://user-images.githubusercontent.com/23651625/106731589-38197800-6642-11eb-8074-4d65c5043d50.png)

**Comment by tonychill** [comment]
A quick fix might be to use some js to select the element on the fly and set the top or bottom CSS property appropriately based on the scroll position of the wrapping element on the screen.

**Comment by hernansartorio** [comment]
Sorry for the delay. You can achieve that by customizing the CSS of the popover, something like:

```
.nice-dates-popover {
  top: 0;
}
```
