### ISSUE TITLE
Props for disable navigate month

### ISSUE THREAD

**Issue by dungmidside** [hernansartorio/react-nice-dates#58]
Hi everyone,

I'm using `DatePickerCalendar`, I want to disable month navigation, I check the API references but can't find any prop for this.

Is there any way to archive this without wait new version to add this props ?

**Comment by davidtranjs** [comment]
dead library 😢

**Comment by hernansartorio** [comment]
Sorry I haven't had time to maintain the library lately, but I'm planning to pick it up again later this year.

As for your original question, you could hide/disable the month navigation with CSS.

**Comment by mustakimkr** [comment]
> Sorry I haven't had time to maintain the library lately, but I'm planning to pick it up again later this year.
> 
> As for your original question, you could hide/disable the month navigation with CSS.

Good to hear from you

**Comment by mustakimkr** [comment]
> > Sorry I haven't had time to maintain the library lately, but I'm planning to pick it up again later this year.
> > As for your original question, you could hide/disable the month navigation with CSS.
> 
> Good to hear from you

I almost decided to cut this from my projects :)

**Comment by davidtranjs** [comment]
Closed as I solved this by CSS
