### ISSUE TITLE
Getting errors and warnings

### ISSUE THREAD

**Issue by leibole** [hernansartorio/react-nice-dates#7]
Hi, 
I really wanted to use this library, it looks great, but I get a loop of a warning and an error, like in the included picture/

If this is solved I would definitely use it.
![image](https://user-images.githubusercontent.com/23569394/73119641-82ffaa80-3f6d-11ea-9234-9cf4d7cdcfce.png)

**Comment by hernansartorio** [comment]
Hi, can you show me the code you‘re using? But try updating your version of date-fns to see if it solves it (the latest version is 2.9.0).

**Comment by leibole** [comment]
As simple as possible:
```
              <DatePicker
                date={eventDate}
                // format="dd-MM-yyyy"
                onDateChange={setEventDate}
                locale={enUS}
              >
                {({ inputProps, focused }) => (
                  <Input
                    className={"input" + (focused ? " -focused" : "")}
                    {...inputProps}
                  />
                )}
              </DatePicker>
```

**Comment by leibole** [comment]
Update after upgrading version: still the same behavior.

**Comment by hernansartorio** [comment]
Sorry for the delay.

Hm, is `eventDate` a string maybe?

**Comment by leibole** [comment]
Yap, I believe it is.

**Comment by leibole** [comment]
Update: the initial value was an empty string. After changing it to null, the warning pour went away. Thank you!

**Comment by hernansartorio** [comment]
Awesome!
